sync:
  # Interval in minutes between sync operations
  interval: 60
  # Cache location for temporary files (inside the container)
  cache_location: /var/cache/pihole-sync

# Main Pi-hole instance (source)
main:
  host: main-pihole.example.com
  schema: https
  port: 443
  api_key: YOUR_MAIN_PIHOLE_APP_PASSWORD

# Secondary Pi-hole instances (targets)
secondary:
  - host: secondary-pihole.example.com
    schema: https
    port: 443
    api_key: YOUR_SECONDARY_PIHOLE_APP_PASSWORD
    update_gravity: true
