name: Binary

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build - ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive-name: pihole-sync-x86_64-linux.tar.gz
          - target: aarch64-unknown-linux-gnu
            archive-name: pihole-sync-arm64-linux.tar.gz
          - target: armv7-unknown-linux-gnueabihf
            archive-name: pihole-sync-armv7-linux.tar.gz

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../${{ matrix.archive-name }} pihole-sync
          cd -

      # Find the manually created release by tag
      - name: Find release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        id: find_release
        run: |
          TAG="${GITHUB_REF#refs/tags/}"

          # Try to find the existing release
          RELEASE_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG")

          # Check if release exists
          if [[ $(echo $RELEASE_DATA | jq -r '.id') != "null" ]]; then
            UPLOAD_URL=$(echo $RELEASE_DATA | jq -r '.upload_url')
            # Remove the {?name,label} part
            UPLOAD_URL=${UPLOAD_URL%\{*\}}
            echo "upload_url=$UPLOAD_URL" >> $GITHUB_OUTPUT
            echo "Release found for tag $TAG"
          else
            echo "::error::No release found for tag $TAG"
            exit 1
          fi

      # Upload the asset to the manually created release
      - name: Upload Release Asset
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.find_release.outputs.upload_url }}
          asset_path: ${{ matrix.archive-name }}
          asset_name: ${{ matrix.archive-name }}
          asset_content_type: application/gzip
